include: package:flutter_lints/flutter.yaml


# analyzer:
#   strong-mode:
#     # Will become the default once non-nullable types land
#     # https://github.com/dart-lang/sdk/issues/31410#issuecomment-510683629
#     implicit-casts: false
#   errors:
#     # treat missing required parameters as a warning (not a hint)
#     missing_required_param: warning
#     # treat missing returns as a warning (not a hint)
#     missing_return: warning

# # Rules are in the same order (alphabetically) as documented at http://dart-lang.github.io/linter/lints
# # and https://github.com/dart-lang/linter/blob/master/example/all.yaml
linter:
  rules: